[font]
normal = {family = "DroidSans Mono", style = "Light"}
bold = {family = "DroidSans Mono", style = "Light"}
italic = {family = "DroidSans Mono", style = "Light"}
size = 9
offset = { x = 1, y = -2 } 

[general]
import = [
  "~/.config/alacritty/vscode.toml"
]
