[font]
normal = {family = "Droid Sans Mono"}
bold = {family = "Droid Sans Mono", style = "Regular"}
italic = {family = "Droid Sans Mono", style = "Regular"}
size = 8.8
offset = { x = 1, y = -1 } 

[general]
import = [
  "~/.config/alacritty/vscode.toml"
]
