import = [
  "~/.config/alacritty/sonokai.toml"
]

[font]
normal = {family = "SauceCodePro Nerd Font"}
bold = {family = "SauceCodePro Nerd Font", style = "Normal"}
size = 10
offset = { x = 1, y = -2 } 
